# =============================================================================
# SHARED CONFIGURATION FILES
# =============================================================================

# -----------------------------------------------------------------------------
# shared/application-dev.yml (Development Shared Configuration)
# -----------------------------------------------------------------------------
spring:
  profiles: dev
  
  # Database Configuration
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: ${spring.application.name}-cp
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Logging Configuration
logging:
  level:
    com.retailstore: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE